[package]
name = "bits"
version = "0.1.0"
edition = "2021"

[features]
default = ["half"]
half = ["dep:half"]

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
half = { version = "2.3.1", optional = true }
termcolor = "1.4.0"
